[workspace]

members = [
	"basics",
	"boxes",
	"closures",
	"dereferencing",
	"dropping",
	"enums",
	"iterators",
	"loops",
	"multiple_owners",
	"project_guessing_game",
	"project_minigrep",
	"ownership",
	"testing",
	"threads",
	"vectors"
]